-- Personal Finance Tracker - Seed Data
USE PersonalFinanceTracker;
GO

-- Seeded accounts. The Admin password hash below was generated by actually
-- running PasswordHasher<string>.HashPassword for 'Admin@123' in a throwaway
-- console app (deleted afterward) - not hand-typed - so the seeded admin can
-- actually log in with the documented password on a fresh database.
SET IDENTITY_INSERT dbo.Users ON;

INSERT INTO dbo.Users (Id, Name, Email, PasswordHash, Role, IsActive) VALUES
(1, N'Admin', N'admin@financetrack.local', N'AQAAAAEAACcQAAAAEM1djq0lZXo+dJOfS8WwF4HUwdEUdqyevXA+6Dl3FD7FDtB2if2PUGwb6IluqmiegA==', N'Admin', 1),
(2, N'Demo User', N'demo@financetrack.local', N'AQAAAAEAACcQAAAAEM1djq0lZXo+dJOfS8WwF4HUwdEUdqyevXA+6Dl3FD7FDtB2if2PUGwb6IluqmiegA==', N'User', 1);

SET IDENTITY_INSERT dbo.Users OFF;
GO

-- All of the sample financial data below belongs to the Demo User (Id = 2) -
-- an Admin account never has income/expense/categories/accounts of its own.
SET IDENTITY_INSERT dbo.Categories ON;

INSERT INTO dbo.Categories (Id, UserId, Name, Type, Color) VALUES
(1, 2, N'Salary',       N'Income',  N'#22c55e'),
(2, 2, N'Freelance',    N'Income',  N'#10b981'),
(3, 2, N'Investments',  N'Income',  N'#14b8a6'),
(4, 2, N'Groceries',    N'Expense', N'#ef4444'),
(5, 2, N'Rent',         N'Expense', N'#f97316'),
(6, 2, N'Utilities',    N'Expense', N'#eab308'),
(7, 2, N'Transport',    N'Expense', N'#3b82f6'),
(8, 2, N'Entertainment',N'Expense', N'#a855f7');

SET IDENTITY_INSERT dbo.Categories OFF;

SET IDENTITY_INSERT dbo.Accounts ON;

INSERT INTO dbo.Accounts
(
    Id,
    UserId,
    Name,
    AccountType,
    InitialBalance,
    Balance
)
VALUES
(1, 2, N'Primary Checking',   N'Checking', 4250.00, 4250.00),
(2, 2, N'Emergency Savings',  N'Savings',  12000.00, 12000.00),
(3, 2, N'Credit Card',        N'Credit',   -850.00,  -850.00);

SET IDENTITY_INSERT dbo.Accounts OFF;

INSERT INTO dbo.Transactions (UserId, AccountId, CategoryId, Amount, Description, TransactionDate, TransactionType) VALUES
(2, 1, 1, 5200.00, N'Monthly salary deposit',       DATEADD(DAY, -25, CAST(GETDATE() AS DATE)), N'Income'),
(2, 1, 4,  156.42, N'Weekly groceries',             DATEADD(DAY, -20, CAST(GETDATE() AS DATE)), N'Expense'),
(2, 1, 5, 1500.00, N'Apartment rent',               DATEADD(DAY, -18, CAST(GETDATE() AS DATE)), N'Expense'),
(2, 1, 7,   45.00, N'Bus pass',                     DATEADD(DAY, -15, CAST(GETDATE() AS DATE)), N'Expense'),
(2, 2, 3,  500.00, N'Dividend reinvestment',        DATEADD(DAY, -12, CAST(GETDATE() AS DATE)), N'Income'),
(2, 1, 6,   89.50, N'Electric & internet bill',     DATEADD(DAY, -10, CAST(GETDATE() AS DATE)), N'Expense'),
(2, 1, 8,   35.00, N'Streaming subscription',       DATEADD(DAY, -7,  CAST(GETDATE() AS DATE)), N'Expense'),
(2, 1, 2,  750.00, N'Freelance web project',        DATEADD(DAY, -5,  CAST(GETDATE() AS DATE)), N'Income'),
(2, 3, 4,   62.30, N'Restaurant dinner',            DATEADD(DAY, -3,  CAST(GETDATE() AS DATE)), N'Expense'),
(2, 1, 4,  112.18, N'Costco run',                   DATEADD(DAY, -1,  CAST(GETDATE() AS DATE)), N'Expense');
GO
